bundler_args: --retry=3 --jobs=3
cache: bundler
language: ruby
sudo: false
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  slack:
    secure: wZ1UPEcH/Zf/wSPvpR1q76vpUQvAEGuwR5500ML8C+shW7PedvuSZaiZYAOZxhyD17RXzXYroON0ArEk3NUcKD8supPzYjUWzCeWDIFaYxEb7dOm7tpRBf4GuQ/oy8HGsBi947ZTX3WytGWZU0q0aRu2EirPcoY05vzley/hYTI=
